"""add platform fields to users table

Revision ID: 56b9e86e5425
Revises: 0cf9c0be220d
Create Date: 2025-05-10 17:51:38.674127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b9e86e5425'
down_revision: Union[str, None] = '0cf9c0be220d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('metrics', sa.Column('collected_at', sa.TIMESTAMP(timezone=True), nullable=False))
    op.create_index(op.f('ix_metrics_collected_at'), 'metrics', ['collected_at'], unique=False)
    op.create_index(op.f('ix_metrics_platform_id'), 'metrics', ['platform_id'], unique=False)
    op.create_index(op.f('ix_metrics_user_id'), 'metrics', ['user_id'], unique=False)
    op.create_foreign_key(None, 'metrics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('metrics', 'date')
    op.add_column('users', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('platform_user_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'users', 'platforms', ['platform_id'], ['id'])
    op.create_unique_constraint('uq_users_platform', 'users', ['platform_id', 'platform_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_platform', 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'platform_user_id')
    op.drop_column('users', 'platform_id')
    op.add_column('metrics', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_index(op.f('ix_metrics_user_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_platform_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_collected_at'), table_name='metrics')
    op.drop_column('metrics', 'collected_at')
    op.drop_column('metrics', 'user_id')
    # ### end Alembic commands ###
